- name: DYNAMIC-DOCKER-CONFIGURATION
  hosts: localhost
  vars_prompt:
          - name: CONTAINER_NAME
            prompt: "Enter name of container "
            private: no
          - name: IMAGE_NAME
            prompt: "Enter name of image "
            private: no
          - name: TAG
            prompt: "Enter tag name "
            private: no
  tasks:
          - name: TO INSTALL THE DOCKER SDK
            block:
              - command: pip3 show docker-py
            rescue:
             - pip:
                name: docker-py        
          - name: TO START THE DOCKER SERVICES 
            service:
               name: "docker"
               state: started
               enabled: yes
            register: b
          - debug:
                var: b.state

          - name: TO PUT THE SELINUX IN PERMISSIVE MODE 
            ansible.posix.selinux:
                    policy: targeted
                    state: permissive
            register: c
          - debug:
                  var: c.state

          - name: TO CREATING IMAGE WITH DOCKER FILE 
            community.general.docker_image:
                    name: "{{ image_name }}"
                    build:
                            path: "/dws/"
                    tag: "{{ tag }}"
                    source: build
            register: r
          - debug:
                  var: r

          - name: TO LAUCHING A DOCKER CONTAINER 
            command: docker run -itd --name {{ cont_name }} -p 2020:22 {{ image_name }}:{{ tag }} 
            register: e
          - debug:
                   var: e

          - name: TO RETRIVE THE NNEW IP OF RUNNING CONTAINER 
            community.general.docker_container_info:
                     name: "{{ cont_name }}"
            register: f
          - debug:
                   var: f.container.NetworkSettings.IPAddress  

          - name: TO UPADTE THE INVENTORY FILE 
            blockinfile:
                     path: /etc/hosts.txt
                     block: |
                             [docker]
                             {{ f['container']['NetworkSettings']['IPAddress'] }} ansible_ssh_user=root ansible_ssh_pass=root  ansible_connection=ssh

            register: g
          - debug:
                   var: g.msg


